apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: klemen1999/restaurant-frontend:2023-01-06-16-56-13
          name: frontend
          ports:
            - containerPort: 3000
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: server
  selector:
    app: frontend
